# Generated by Django 3.0.3 on 2020-07-30 05:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('single', 'Single'), ('equal', 'equal'), ('random', 'Random')], default='single', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_invoice', to='cases.task')),
            ],
        ),
        migrations.CreateModel(
            name='invoice_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_due_date', models.DateTimeField(null=True)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_payment', to='case_settings.task_invoice')),
            ],
        ),
    ]
