# Generated by Django 3.0.3 on 2020-07-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscription',
        ),
    ]
