# Generated by Django 3.0.3 on 2020-08-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_invoice',
            name='category',
            field=models.CharField(choices=[('single', 'Single'), ('equal', 'equal'), ('random', 'Random')], max_length=6),
        ),
    ]
