# Generated by Django 3.0.3 on 2020-08-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_settings', '0002_auto_20200804_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_invoice',
            name='category',
            field=models.CharField(choices=[('single', 'Single'), ('equal', 'equal'), ('random', 'Random')], default='single', max_length=6),
        ),
    ]
