# Generated by Django 3.0.3 on 2020-08-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_settings', '0003_auto_20200804_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_payment',
            old_name='payment_due_date',
            new_name='due_date',
        ),
    ]
