# Generated by Django 3.0.3 on 2020-08-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_settings', '0004_auto_20200806_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_payment',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
