# Generated by Django 3.0.3 on 2020-08-07 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_settings', '0005_auto_20200806_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_invoice',
            name='frequency',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
