# Generated by Django 3.0.3 on 2020-07-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_case_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='billing_type',
            field=models.CharField(choices=[('non billing', 'Non Billing'), ('billing', 'Billing')], default='non billing', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='invoice_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('onetime', 'Onetime')], default='onetime', max_length=16, null=True),
        ),
    ]
