# Generated by Django 3.0.3 on 2020-08-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20200801_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklist_items',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='billing_type',
            field=models.CharField(choices=[('non billing', 'Non Billing'), ('billing', 'Billing')], max_length=16, null=True),
        ),
    ]
