# Generated by Django 3.0.3 on 2020-08-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20200803_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='complete',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
