# Generated by Django 3.0.3 on 2020-08-04 03:43

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20200804_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=5, upload_to=cases.models.path_file_name),
        ),
    ]
