# Generated by Django 3.0.3 on 2020-08-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20200804_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='time_spent',
            field=models.TimeField(null=True),
        ),
    ]
