# Generated by Django 3.0.3 on 2020-08-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_timer_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
