# Generated by Django 3.0.3 on 2020-08-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_auto_20200806_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_activity',
            name='target',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
