# Generated by Django 3.0.3 on 2020-08-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_task_activity_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
