# Generated by Django 3.0.3 on 2020-07-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('case', models.IntegerField()),
                ('case_member', models.IntegerField()),
                ('case_clients', models.IntegerField()),
                ('task', models.IntegerField()),
                ('task_members', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('time_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('both', 'Both')], max_length=16)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('yearly_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
