from django.urls import path
from .views import *
from rest_framework.authtoken import views as tokenviews

urlpatterns = [
    path('add_case/', create_Case.as_view(), name='new_case'),
    path('show_cases/', show_cases.as_view(), name='show_cases'),
    path('case/<int:case_id>/', show_case.as_view(), name='show_case'),
    path('search/', search_case.as_view(), name='search_case'),
    path('members/', members.as_view(), name='members'),
    path('clients/', clients.as_view(), name='clients'),
    path('case_members/<int:case_id>/', case_assign_members.as_view(), name='case_members'),
    path('case_clients/<int:case_id>/', case_assign_clients.as_view(), name='case_clients'),
    path('case_admin/<int:case_id>/<int:user_id>/', case_admin.as_view(), name='case_admin'),
    path('add_task/<int:case_id>/', add_task.as_view(), name='add_task'),
    path('task_members/<int:task_id>/', add_task_members.as_view(), name='add_task_members'),
    path('task/<int:task_id>/', show_task_complete.as_view(), name='task_complete'),
    path('today_tasks/', today_tasks.as_view(), name='today_tasks'),
    path('active_tasks/', show_active_tasks.as_view(), name='active_tasks'),
    path('search_task/', search_tasks.as_view(), name='search_tasks'),
    path('task_comment/<int:task_id>/', add_task_comment.as_view(), name='add_task_comment'),
    path('edit_task_comment/<int:comment_id>/', edit_task_comment.as_view(), name='edit_task_comment'),
    path('task_checklist/<int:task_id>/', add_task_checklist.as_view(), name='add_task_checklist'),
    path('edit_task_checklist/<int:checklist_id>/', edit_task_checklist.as_view(), name='edit_task_checklist'),
    path('task_checklist_items/<int:checklist_id>/', add_task_checklist_items.as_view(), name='add_task_checklist_items'),
    path('edit_checklist_items/<int:checklist_item_id>/', edit_checklist_items.as_view(), name='edit_task_checklist_items'),
    path('task_label/<int:task_id>/', add_task_label.as_view(), name='add_task_label'),
    path('delete_task_label/<int:label_id>/', delete_task_labels.as_view(), name='delete_task_label'),
    path('task_timer/<int:task_id>/<str:action>/', task_timer.as_view(), name='add_task_timer'),
    path('task_image/<int:task_id>/', Image.as_view(), name='add_task_image'),
    path('image/<int:img_id>/', delete_Image.as_view(), name='delete_image'),
    path('task_document/<int:task_id>/', Document.as_view(), name='add_task_document'),
    path('document/<int:doc_id>/', delete_Document.as_view(), name='delete_document'),
    path('activity/<int:case_id>/', show_case_activity.as_view(), name='show_case_activity'),
    path('task_complete/<int:task_id>/', task_completed.as_view(), name='task_complete'),
    path('case_complete/<int:case_id>/', case_completed.as_view(), name='case_completed'),
    path('closed_cases/', closed_cases.as_view(), name='closed_cases'),
]
